// Icons for the soft skills, the art corner and achievements.
export const ITEMS = {
  clipboard: [
    "...kkkkk...",
    ".kkkyyykkk.",
    ".kwwkkkwwk.",
    ".kwwwwwwwk.",
    ".kwgwkkkwk.",
    ".kwwwwwwwk.",
    ".kwgwkkkwk.",
    ".kwwwwwwwk.",
    ".kwpwkkkwk.",
    ".kwwwwwwwk.",
    ".kkkkkkkkk.",
  ],
  shield: [
    ".kkkkkkkkk.",
    "kbbbbwbbbbk",
    "kbbbbwbbbbk",
    "kbbbbwbbbbk",
    "kwwwwwwwwwk",
    "kbbbbwbbbbk",
    ".kbbbwbbbk.",
    ".kbbbwbbbk.",
    "..kbbwbbk..",
    "...kbwbk...",
    "....kwk....",
    ".....k.....",
  ],
  heart: [
    ".kk...kk.",
    "kppk.kppk",
    "kpwpkpppk",
    "kpppppppk",
    ".kpppppk.",
    "..kpppk..",
    "...kpk...",
    "....k....",
  ],
  palette: [
    "...kkkkkk...",
    ".kknnnnnnkk.",
    "knnppnnbbnnk",
    "knnppnnbbnnk",
    "knnnnnnnnnnk",
    "knyynnkkknnk",
    "knyynnkknnnk",
    "knnnnnnnggnk",
    ".knnnnnnggk.",
    "..kkkkkkkk..",
  ],
  trophy: [
    "..kkkkkkk..",
    "kkkywyyykkk",
    "k.kywyyyk.k",
    "k.kyyyyyk.k",
    ".kkyyyyykk.",
    "...kyyyk...",
    "....kyk....",
    "....kyk....",
    "...kkkkk...",
    "..kkkkkkk..",
  ],
} satisfies Record<string, string[]>;