// Icons for the technical skills and projects.
export const TECH = {
  chip: [
    "..k.k.k.k..",
    ".kkkkkkkkk.",
    "kkgggggggkk",
    ".kgggggggk.",
    "kkggkkkggkk",
    ".kggkykggk.",
    "kkggkkkggkk",
    ".kgggggggk.",
    "kkgggggggkk",
    ".kkkkkkkkk.",
    "..k.k.k.k..",
  ],
  monitor: [
    "kkkkkkkkkkkk",
    "kbbbbbbbbbbk",
    "kbwwbbbbbbbk",
    "kbbbbbbbbbbk",
    "kbyyyyybbbbk",
    "kbbpppbbbbbk",
    "kbbbbbbbbbbk",
    "kkkkkkkkkkkk",
    "....kkkk....",
    "..kkkkkkkk..",
  ],
  radar: [
    "...kkkkk...",
    ".kkdddddkk.",
    ".kddddgddk.",
    "kdddddgdddk",
    "kddpddgdddk",
    "kdddddgggdk",
    "kdddddddddk",
    "kddddddpddk",
    ".kdddddddk.",
    ".kkdddddkk.",
    "...kkkkk...",
  ],
  antenna: [
    "..kkkkkkk..",
    ".k.......k.",
    "k..kkkkk..k",
    "..k.....k..",
    "....kkk....",
    "...k...k...",
    ".....p.....",
    "....ppp....",
    ".....k.....",
    ".....k.....",
    "...kkkkk...",
  ],
  // Ohm, the robot pet, with its happy face (same art as ohm/src/components/OhmSprite.tsx).
  ohm: [
    "...........kk...........",
    "..........kywk..........",
    "..........kyyk..........",
    "...........kk...........",
    "...........kk...........",
    "...kkkkkkkkkkkkkkkkkk...",
    "..kwwbbbbbbbbbbbbbbbbk..",
    ".kwbbbbbbbbbbbbbbbbbbuk.",
    ".kwbkkkkkkkkkkkkkkkkbuk.",
    ".kbbkeeeeeeeeeeeeeekbuk.",
    "kkbbkeeaaaeeeeaaaeekbukk",
    "kkbbkeaeeeaeeaeeeaekbukk",
    "kkbbkeeeeeeeeeeeeeekbukk",
    "kkbbkeeeeeaeeaeeeeekbukk",
    ".kbbkeeeeeeaaeeeeeekbuk.",
    ".kbbkkkkkkkkkkkkkkkkbuk.",
    ".kbrrbbbbbbbbbbbbbbrruk.",
    ".kbbbbbbbbbbbbbbbbbbbuk.",
    "..kuuuuuuuuuuuuuuuuuuk..",
    "...kkkkkkkkkkkkkkkkkk...",
    "......kwbbbbbbbbuk......",
    "...kkkkbbbyyyybbukkkk...",
    "...kbbkbbybbbbybukbuk...",
    "...kbbkbbybbbbybukbuk...",
    "...kkkkbbbybbybbukkkk...",
    "......kbbyybbyybuk......",
    "......kuuuuuuuuuuk......",
    "......kkkkkkkkkkkk......",
    ".......kbbk..kbbk.......",
    ".......kkkk..kkkk.......",
  ],
} satisfies Record<string, string[]>;